<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_cliententity_continue</name>
   <tag></tag>
   <elementGuidId>b5ccfca5-d3dd-4857-bef5-d585580c3f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//button[@id='continue_customer_entity_button']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
