<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_confusage_saveconfusage</name>
   <tag></tag>
   <elementGuidId>c02df90d-711b-4c01-9841-2eb523599231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//input[@id='btn_panel4_saveUsage']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
