<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_configuredata_continue</name>
   <tag></tag>
   <elementGuidId>def2ec3e-2c20-4b11-925e-800a444ff73b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//button[@id='btn_panel2_continue']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
