<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_confusage_continue</name>
   <tag></tag>
   <elementGuidId>60c7be07-1456-48ac-b81f-243f93795ebf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//input[@id='btn_panel4_save']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
