<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confusage_selectedfields</name>
   <tag></tag>
   <elementGuidId>4848d68e-f667-4833-a761-4482f7ad7e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//select[@id='filter_configure_usage_selected_fields_for']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
