<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>payroll_type</name>
   <tag></tag>
   <elementGuidId>9e333987-61a4-4610-bef6-35ca0dd75aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html//div[@id='showPayroll_modal']/div[@class='modal-body']/label[2]/select</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
